# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='search',
            new_name='search_recipe',
        ),
    ]
