# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 13:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0002_auto_20160110_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Last_name', models.CharField(blank=True, max_length=15, null=True)),
                ('First_name', models.CharField(blank=True, max_length=15, null=True)),
                ('Departement', models.CharField(blank=True, max_length=15, null=True)),
                ('Adress', models.CharField(blank=True, max_length=15, null=True)),
                ('Room_number', models.CharField(blank=True, max_length=5, null=True)),
                ('Telephone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='search',
            name='search_recipe',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
