# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20160113_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='Adress',
        ),
        migrations.AlterField(
            model_name='information',
            name='Room_number',
            field=models.CharField(max_length=5),
        ),
    ]
