# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_auto_20160113_1614'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
