# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 17:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0005_delete_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='information',
            name='Room_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='information',
            name='Telephone_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
