# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_auto_20160114_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
