# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_auto_20160114_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient',
            field=models.CharField(max_length=20),
        ),
    ]
